version: "3.9"

services:
  front:
    build:
      context: ./front
      dockerfile: ./Dockerfile
    image: front:lts
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./front:/app/run
    links:
      - back
    depends_on:
      - back

  back:
    build:
      context: ./back
      dockerfile: ./Dockerfile
    image: back:lts
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5432/${POSTGRES_DB}?schema=public"
    volumes:
      - ./back:/app/run
    links:
      - postgres
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    driver: local
